spring.application.name=backend-api
spring.datasource.url=jdbc:postgresql://ep-falling-snowflake-a8t5hm8k-pooler.eastus2.azure.neon.tech/neondb?user=neondb_owner&password=npg_rmqG92ubRHTU&sslmode=require
spring.jpa.hibernate.ddl-auto=update